[build]
builder = "NIXPACKS"
buildCommand = "npm ci --omit=dev --no-audit"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[service]
internal_port = 3000
auto_deploy = true

[phases]
setup = [
  "nodejs_22",
  "npm-9_x"
]

[phases.setup.nixpacksConfig]
nodejs_version = "18.x"